[package]
name = "wit-bindgen-cli"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
description = "A language bindings generator for wit."

[workspace]
members = [
  "crates/test-rust-wasm",
  "crates/wit-bindgen-demo",
  "crates/wit-component",
]
resolver = "2"

[[bin]]
name = "wit-bindgen"
test = false

[dependencies]
anyhow = "1.0"
structopt = { version = "0.3", default-features = false }
wit-bindgen-core = { path = 'crates/bindgen-core' }
wit-bindgen-gen-guest-rust = { path = 'crates/gen-guest-rust', features = ['structopt'] }
wit-bindgen-gen-host-wasmtime-rust = { path = 'crates/gen-host-wasmtime-rust', features = ['structopt'] }
wit-bindgen-gen-host-wasmtime-py = { path = 'crates/gen-host-wasmtime-py', features = ['structopt'] }
wit-bindgen-gen-host-js = { path = 'crates/gen-host-js', features = ['structopt'] }
wit-bindgen-gen-guest-c = { path = 'crates/gen-guest-c', features = ['structopt'] }
wit-bindgen-gen-markdown = { path = 'crates/gen-markdown', features = ['structopt'] }
wit-bindgen-gen-guest-spidermonkey-js = { path = 'crates/gen-guest-spidermonkey-js', features = ['structopt'] }
wit-bindgen-gen-host-wasmer-rust = { path = 'crates/gen-host-wasmer-rust', features = ['structopt'] }
wit-bindgen-gen-host-wasmer-py = { path = 'crates/gen-host-wasmer-py', features = ['structopt'] }

# Compiling `spidermonkey.wasm` takes way too long without this.
[profile.dev.package.cranelift-codegen]
debug-assertions = false
opt-level = 2

[package.metadata.wapm]
namespace = "wasmer"
abi = "wasi"
