[package]
name = "linera-wit-bindgen-cli"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2021"
description = "A language bindings generator for wit."

[workspace]
members = [
  "crates/test-rust-wasm",
  "crates/wit-bindgen-demo",
  "crates/wit-component",
]
resolver = "2"

[[bin]]
name = "wit-bindgen"
test = false

[dependencies]
anyhow = "1.0"
structopt = { version = "0.3", default-features = false }
linera-wit-bindgen-core = { path = 'crates/bindgen-core' }
linera-wit-bindgen-gen-guest-rust = { path = 'crates/gen-guest-rust', features = ['structopt'] }
linera-wit-bindgen-gen-host-wasmtime-rust = { path = 'crates/gen-host-wasmtime-rust', features = ['structopt'] }
linera-wit-bindgen-gen-host-wasmtime-py = { path = 'crates/gen-host-wasmtime-py', features = ['structopt'] }
linera-wit-bindgen-gen-host-js = { path = 'crates/gen-host-js', features = ['structopt'] }
linera-wit-bindgen-gen-guest-c = { path = 'crates/gen-guest-c', features = ['structopt'] }
linera-wit-bindgen-gen-markdown = { path = 'crates/gen-markdown', features = ['structopt'] }
linera-wit-bindgen-gen-host-wasmer-rust = { path = 'crates/gen-host-wasmer-rust', features = ['structopt'] }
linera-wit-bindgen-gen-host-wasmer-py = { path = 'crates/gen-host-wasmer-py', features = ['structopt'] }

[package.metadata.wapm]
namespace = "wasmer"
abi = "wasi"
