[package]
name = "linera-wit-bindgen-gen-guest-c"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
wit-bindgen-core = { path = '../bindgen-core', version = '0.2.0', package = "linera-wit-bindgen-core" }
heck = "0.3"
structopt = { version = "0.3", default-features = false, optional = true }

[dev-dependencies]
test-helpers = { path = '../test-helpers', features = ['guest-c'], package = "linera-test-helpers" }
