[package]
name = "wit-bindgen-guest-rust"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
wit-bindgen-guest-rust-macro = { path = "../guest-rust-macro", optional = true }
bitflags = "1.3"

[features]
default = ["macros"]
macros = ["wit-bindgen-guest-rust-macro"]
